# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Compilers and History
tagline:             'Nickiks Blog'
description:         '-'
url:                 https://nickik.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              'Niklaus Zbinden'
  url:               nickik.github.io
  email:             niklaus.zbinden@gmail.com

# Custom vars
version:             1.0.0
